-- HostOS — migration 0019: the shared workspace layer
-- Additive and idempotent. Safe to run twice.
--
-- Three things both products (fleet operations and restaurant operations)
-- need and neither had as data: notifications that outlive the browser tab
-- that raised them, tasks a team can hand each other, and a dashboard layout
-- a person can arrange once and keep.

-- ========================================================== notifications

-- Every event worth a person's attention, from any module, in one table.
--
-- Until now "notifications" was a Gmail view, desktop pings lived in the
-- extension, and email alerts were recorded only as sent/not-sent. Nothing
-- gave a co-host who logged in at 9am the list of what happened overnight.
create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references hosts(id) on delete cascade,
  -- Null means "everyone on this fleet". An address targets one member —
  -- used for mentions and personal reminders.
  user_email text,
  -- 'trip' | 'message' | 'alert' | 'restaurant' | 'order' | 'task' | 'system' | 'butler'
  kind text not null,
  -- 'info' | 'success' | 'warning' | 'critical'
  severity text not null default 'info',
  title text not null,
  body text,
  -- Where clicking it goes. A HostOS route, or a turo.com / DoorDash URL.
  href text,
  -- Stable key so the same underlying fact is never inserted twice
  -- ("licence:57760996", "store_paused:<restaurant_id>:<date>").
  dedupe_key text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table notifications enable row level security;

create unique index if not exists notifications_dedupe_idx
  on notifications (host_id, dedupe_key) where dedupe_key is not null;
create index if not exists notifications_inbox_idx
  on notifications (host_id, created_at desc);
create index if not exists notifications_unread_idx
  on notifications (host_id, user_email) where read_at is null;

-- ================================================================== tasks

-- The unit of work. Generated by the AI Butler from what it sees (an
-- unverified licence, a store paused during service), by an automation rule,
-- or typed by a person. Every task names where it came from so a generated
-- one can be regenerated or dismissed as a class rather than one by one.
create table if not exists tasks (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references hosts(id) on delete cascade,
  title text not null,
  description text,
  -- 'open' | 'in_progress' | 'done' | 'dismissed'
  status text not null default 'open',
  -- 'low' | 'medium' | 'high' | 'critical'
  priority text not null default 'medium',
  due_at timestamptz,
  assignee_email text,
  -- 'manual' | 'butler' | 'automation'
  source text not null default 'manual',
  -- What the task is about, so the UI can deep-link: ('trip', '57760996'),
  -- ('restaurant', '<uuid>'), ('order', '<uuid>').
  related_kind text,
  related_id text,
  href text,
  -- Same purpose as notifications.dedupe_key: the Butler must be able to
  -- re-run without creating the same task twice.
  dedupe_key text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table tasks enable row level security;

create unique index if not exists tasks_dedupe_idx
  on tasks (host_id, dedupe_key) where dedupe_key is not null;
create index if not exists tasks_board_idx
  on tasks (host_id, status, priority, due_at);

drop trigger if exists tasks_set_updated_at on tasks;
create trigger tasks_set_updated_at before update on tasks
  for each row execute function set_updated_at();

-- ====================================================== dashboard layouts

-- One row per (fleet, person): which widgets are visible and in what order.
-- The catalogue of widgets lives in code; this stores only the arrangement,
-- so a widget that is removed from the catalogue is simply ignored on read.
create table if not exists dashboard_layouts (
  host_id uuid not null references hosts(id) on delete cascade,
  user_email text not null,
  layout jsonb not null default '[]',
  updated_at timestamptz not null default now(),
  primary key (host_id, user_email)
);

alter table dashboard_layouts enable row level security;

drop trigger if exists dashboard_layouts_set_updated_at on dashboard_layouts;
create trigger dashboard_layouts_set_updated_at before update on dashboard_layouts
  for each row execute function set_updated_at();

-- ======================================================= activity feed

-- Cross-module activity, one line per event, for the dashboard's "Recent
-- events" widget. trip_events stays the fleet's authoritative change log;
-- this is the human-readable stream that the restaurant module and the
-- Butler also write to.
create table if not exists activity_log (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references hosts(id) on delete cascade,
  actor_email text,
  -- 'fleet' | 'restaurant' | 'butler' | 'system' | 'team'
  module text not null,
  -- e.g. 'trip.rescheduled', 'store.paused', 'task.completed', 'draft.sent'
  event text not null,
  description text not null,
  href text,
  payload jsonb,
  occurred_at timestamptz not null default now()
);

alter table activity_log enable row level security;

create index if not exists activity_log_host_idx on activity_log (host_id, occurred_at desc);
